# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-03 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('dt_created', models.DateTimeField(auto_now=True, verbose_name='dt_created')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('file_size', models.BigIntegerField(verbose_name='file_size')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=256, verbose_name='url')),
                ('is_alive', models.BooleanField(default=False, verbose_name='is_alive')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='links',
            field=models.ManyToManyField(related_name='documents', to='crawler.Link', verbose_name='links'),
        ),
    ]
